// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartStepsServer.Data;

#nullable disable

namespace SmartStepsServer.Migrations
{
    [DbContext(typeof(SmartStepsDbContext))]
    [Migration("20260517065915_AddValidationConstraints")]
    partial class AddValidationConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartStepsServer.Data.Models.Flashcard", b =>
                {
                    b.Property<int>("FlashcardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlashcardId"));

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<string>("CorrectFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("OptionA")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OptionB")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SituationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("WrongFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FlashcardId");

                    b.HasIndex("SituationId");

                    b.ToTable("Flashcard", null, t =>
                        {
                            t.HasCheckConstraint("CK_Flashcard_CorrectAnswer", "[CorrectAnswer] IN ('A', 'B')");
                        });
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.Island", b =>
                {
                    b.Property<int>("IslandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IslandId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("IslandId");

                    b.ToTable("Island", null, t =>
                        {
                            t.HasCheckConstraint("CK_Island_Status", "[Status] IN ('Active', 'Hidden')");
                        });
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.ParentReviewQuestion", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("QuestionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SituationId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("SuggestedActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("QuestionId");

                    b.HasIndex("SituationId");

                    b.HasIndex("SkillId");

                    b.ToTable("ParentReviewQuestion", (string)null);
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.Situation", b =>
                {
                    b.Property<int>("SituationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SituationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Intro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IslandId")
                        .HasColumnType("int");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("SituationId");

                    b.HasIndex("IslandId");

                    b.ToTable("Situation", null, t =>
                        {
                            t.HasCheckConstraint("CK_Situation_Status", "[Status] IN ('Draft', 'Pending', 'Approved', 'Rejected', 'Published', 'Hidden')");
                        });
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.SituationSkill", b =>
                {
                    b.Property<int>("SituationId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("SkillId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("SituationId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("SituationSkill", (string)null);
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.SituationStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StepId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("MediaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("SituationId")
                        .HasColumnType("int");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("StepId");

                    b.HasIndex("SituationId");

                    b.ToTable("SituationStep", null, t =>
                        {
                            t.HasCheckConstraint("CK_SituationStep_StepType", "[StepType] IN ('Intro', 'Story', 'Flashcard', 'Result')");
                        });
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("SkillId");

                    b.ToTable("Skill", (string)null);
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN ('Child', 'Parent', 'Admin', 'ContentCreator')");
                        });
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.UserAnswer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("FlashcardId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<string>("SelectedAnswer")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AnswerId");

                    b.HasIndex("FlashcardId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAnswer", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserAnswer_AttemptCount", "[AttemptCount] >= 1");

                            t.HasCheckConstraint("CK_UserAnswer_SelectedAnswer", "[SelectedAnswer] IN ('A', 'B')");
                        });
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.UserProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("int");

                    b.Property<int>("IslandId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastAccessedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("SituationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProgressId");

                    b.HasIndex("CurrentStep");

                    b.HasIndex("IslandId");

                    b.HasIndex("SituationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserProgress", null, t =>
                        {
                            t.HasCheckConstraint("CK_UserProgress_Status", "[Status] IN ('InProgress', 'Completed')");
                        });
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.Flashcard", b =>
                {
                    b.HasOne("SmartStepsServer.Data.Models.Situation", "Situation")
                        .WithMany("Flashcards")
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Situation");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.ParentReviewQuestion", b =>
                {
                    b.HasOne("SmartStepsServer.Data.Models.Situation", "Situation")
                        .WithMany("ParentReviewQuestions")
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartStepsServer.Data.Models.Skill", "Skill")
                        .WithMany("ParentReviewQuestions")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Situation");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.Situation", b =>
                {
                    b.HasOne("SmartStepsServer.Data.Models.Island", "Island")
                        .WithMany("Situations")
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Island");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.SituationSkill", b =>
                {
                    b.HasOne("SmartStepsServer.Data.Models.Situation", "Situation")
                        .WithMany("SituationSkills")
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartStepsServer.Data.Models.Skill", "Skill")
                        .WithMany("SituationSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Situation");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.SituationStep", b =>
                {
                    b.HasOne("SmartStepsServer.Data.Models.Situation", "Situation")
                        .WithMany("SituationSteps")
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Situation");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.User", b =>
                {
                    b.HasOne("SmartStepsServer.Data.Models.User", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.UserAnswer", b =>
                {
                    b.HasOne("SmartStepsServer.Data.Models.Flashcard", "Flashcard")
                        .WithMany("UserAnswers")
                        .HasForeignKey("FlashcardId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartStepsServer.Data.Models.User", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Flashcard");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.UserProgress", b =>
                {
                    b.HasOne("SmartStepsServer.Data.Models.SituationStep", "SituationStep")
                        .WithMany("UserProgresses")
                        .HasForeignKey("CurrentStep")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartStepsServer.Data.Models.Island", "Island")
                        .WithMany("UserProgresses")
                        .HasForeignKey("IslandId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartStepsServer.Data.Models.Situation", "Situation")
                        .WithMany("UserProgresses")
                        .HasForeignKey("SituationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SmartStepsServer.Data.Models.User", "User")
                        .WithMany("UserProgresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Island");

                    b.Navigation("Situation");

                    b.Navigation("SituationStep");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.Flashcard", b =>
                {
                    b.Navigation("UserAnswers");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.Island", b =>
                {
                    b.Navigation("Situations");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.Situation", b =>
                {
                    b.Navigation("Flashcards");

                    b.Navigation("ParentReviewQuestions");

                    b.Navigation("SituationSkills");

                    b.Navigation("SituationSteps");

                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.SituationStep", b =>
                {
                    b.Navigation("UserProgresses");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.Skill", b =>
                {
                    b.Navigation("ParentReviewQuestions");

                    b.Navigation("SituationSkills");
                });

            modelBuilder.Entity("SmartStepsServer.Data.Models.User", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("UserAnswers");

                    b.Navigation("UserProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
